# Generated by Django 5.1.2 on 2024-10-23 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_restaurant_restaurant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="restaurant_type",
            field=models.CharField(
                choices=[
                    ("IN", "Indian"),
                    ("CH", "Chinese"),
                    ("IT", "Italian"),
                    ("GR", "Greek"),
                    ("MX", "Mexican"),
                    ("FF", "Fast Food"),
                    ("OT", "Other"),
                ],
                default="",
                max_length=2,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("income", models.DecimalField(decimal_places=2, max_digits=8)),
                ("datetime", models.DateTimeField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.restaurant",
                    ),
                ),
            ],
        ),
    ]
